// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/audit.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	FlushInterval int32                  `protobuf:"varint,2,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	BufferSize    int32                  `protobuf:"varint,3,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorConfig) Reset() {
	*x = CollectorConfig{}
	mi := &file_internal_contracts_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorConfig) ProtoMessage() {}

func (x *CollectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorConfig.ProtoReflect.Descriptor instead.
func (*CollectorConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorConfig) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *CollectorConfig) GetFlushInterval() int32 {
	if x != nil {
		return x.FlushInterval
	}
	return 0
}

func (x *CollectorConfig) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

type S3SinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3SinkConfig) Reset() {
	*x = S3SinkConfig{}
	mi := &file_internal_contracts_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3SinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3SinkConfig) ProtoMessage() {}

func (x *S3SinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3SinkConfig.ProtoReflect.Descriptor instead.
func (*S3SinkConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{1}
}

func (x *S3SinkConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3SinkConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *S3SinkConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type DBSinkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBSinkConfig) Reset() {
	*x = DBSinkConfig{}
	mi := &file_internal_contracts_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBSinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBSinkConfig) ProtoMessage() {}

func (x *DBSinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBSinkConfig.ProtoReflect.Descriptor instead.
func (*DBSinkConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{2}
}

func (x *DBSinkConfig) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type AuditQueryConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         string                 `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditQueryConfig) Reset() {
	*x = AuditQueryConfig{}
	mi := &file_internal_contracts_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditQueryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditQueryConfig) ProtoMessage() {}

func (x *AuditQueryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditQueryConfig.ProtoReflect.Descriptor instead.
func (*AuditQueryConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditQueryConfig) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *AuditQueryConfig) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *AuditQueryConfig) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditQueryConfig) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AuditQueryConfig) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditQueryConfig) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type AuditQueryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         string                 `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditQueryInput) Reset() {
	*x = AuditQueryInput{}
	mi := &file_internal_contracts_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditQueryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditQueryInput) ProtoMessage() {}

func (x *AuditQueryInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditQueryInput.ProtoReflect.Descriptor instead.
func (*AuditQueryInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{4}
}

func (x *AuditQueryInput) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *AuditQueryInput) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *AuditQueryInput) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditQueryInput) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AuditQueryInput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditQueryInput) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type AuditExportConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditExportConfig) Reset() {
	*x = AuditExportConfig{}
	mi := &file_internal_contracts_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditExportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditExportConfig) ProtoMessage() {}

func (x *AuditExportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditExportConfig.ProtoReflect.Descriptor instead.
func (*AuditExportConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{5}
}

func (x *AuditExportConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AuditExportConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AuditExportConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type AuditExportInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditExportInput) Reset() {
	*x = AuditExportInput{}
	mi := &file_internal_contracts_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditExportInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditExportInput) ProtoMessage() {}

func (x *AuditExportInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditExportInput.ProtoReflect.Descriptor instead.
func (*AuditExportInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{6}
}

func (x *AuditExportInput) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AuditExportInput) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AuditExportInput) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AuditExportInput) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type AuditAnnotateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   map[string]string      `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAnnotateConfig) Reset() {
	*x = AuditAnnotateConfig{}
	mi := &file_internal_contracts_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAnnotateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAnnotateConfig) ProtoMessage() {}

func (x *AuditAnnotateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAnnotateConfig.ProtoReflect.Descriptor instead.
func (*AuditAnnotateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{7}
}

func (x *AuditAnnotateConfig) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AuditAnnotateConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuditAnnotateConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AuditAnnotateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   map[string]string      `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAnnotateInput) Reset() {
	*x = AuditAnnotateInput{}
	mi := &file_internal_contracts_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAnnotateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAnnotateInput) ProtoMessage() {}

func (x *AuditAnnotateInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAnnotateInput.ProtoReflect.Descriptor instead.
func (*AuditAnnotateInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{8}
}

func (x *AuditAnnotateInput) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AuditAnnotateInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuditAnnotateInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         string                 `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_internal_contracts_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{9}
}

func (x *QueryRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *QueryRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *QueryRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *QueryRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_internal_contracts_audit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{10}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_internal_contracts_audit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{11}
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	PipelineId    string                 `protobuf:"bytes,5,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StepName      string                 `protobuf:"bytes,6,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Actor         string                 `protobuf:"bytes,7,opt,name=actor,proto3" json:"actor,omitempty"`
	CorrelationId string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,10,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_internal_contracts_audit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{12}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AuditEvent) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *AuditEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *AuditEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuditEvent) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type AuditQueryOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditQueryOutput) Reset() {
	*x = AuditQueryOutput{}
	mi := &file_internal_contracts_audit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditQueryOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditQueryOutput) ProtoMessage() {}

func (x *AuditQueryOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditQueryOutput.ProtoReflect.Descriptor instead.
func (*AuditQueryOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{13}
}

func (x *AuditQueryOutput) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AuditQueryOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AuditQueryOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuditExportOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exported      int32                  `protobuf:"varint,1,opt,name=exported,proto3" json:"exported,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	BytesTotal    int32                  `protobuf:"varint,4,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditExportOutput) Reset() {
	*x = AuditExportOutput{}
	mi := &file_internal_contracts_audit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditExportOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditExportOutput) ProtoMessage() {}

func (x *AuditExportOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditExportOutput.ProtoReflect.Descriptor instead.
func (*AuditExportOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{14}
}

func (x *AuditExportOutput) GetExported() int32 {
	if x != nil {
		return x.Exported
	}
	return 0
}

func (x *AuditExportOutput) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *AuditExportOutput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AuditExportOutput) GetBytesTotal() int32 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *AuditExportOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuditAnnotateOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Annotations   map[string]string      `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAnnotateOutput) Reset() {
	*x = AuditAnnotateOutput{}
	mi := &file_internal_contracts_audit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAnnotateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAnnotateOutput) ProtoMessage() {}

func (x *AuditAnnotateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAnnotateOutput.ProtoReflect.Descriptor instead.
func (*AuditAnnotateOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{15}
}

func (x *AuditAnnotateOutput) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AuditAnnotateOutput) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AuditAnnotateOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_internal_contracts_audit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{16}
}

func (x *QueryResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dropped       int64                  `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	Buffered      int32                  `protobuf:"varint,2,opt,name=buffered,proto3" json:"buffered,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_internal_contracts_audit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{17}
}

func (x *StatsResponse) GetDropped() int64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *StatsResponse) GetBuffered() int32 {
	if x != nil {
		return x.Buffered
	}
	return 0
}

func (x *StatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SinkInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TableName     string                 `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkInfoResponse) Reset() {
	*x = SinkInfoResponse{}
	mi := &file_internal_contracts_audit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkInfoResponse) ProtoMessage() {}

func (x *SinkInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_audit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkInfoResponse.ProtoReflect.Descriptor instead.
func (*SinkInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_contracts_audit_proto_rawDescGZIP(), []int{18}
}

func (x *SinkInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SinkInfoResponse) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SinkInfoResponse) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SinkInfoResponse) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SinkInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_audit_proto protoreflect.FileDescriptor

const file_internal_contracts_audit_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/audit.proto\x12\x19workflow.plugins.audit.v1\x1a\x1cgoogle/protobuf/struct.proto\"q\n" +
	"\x0fCollectorConfig\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\x12%\n" +
	"\x0eflush_interval\x18\x02 \x01(\x05R\rflushInterval\x12\x1f\n" +
	"\vbuffer_size\x18\x03 \x01(\x05R\n" +
	"bufferSize\"V\n" +
	"\fS3SinkConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"-\n" +
	"\fDBSinkConfig\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\"\xca\x01\n" +
	"\x10AuditQueryConfig\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x02 \x01(\tR\x05until\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"\xc9\x01\n" +
	"\x0fAuditQueryInput\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x02 \x01(\tR\x05until\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"[\n" +
	"\x11AuditExportConfig\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\x99\x01\n" +
	"\x10AuditExportInput\x12=\n" +
	"\x06events\x18\x01 \x03(\v2%.workflow.plugins.audit.v1.AuditEventR\x06events\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"\xe0\x01\n" +
	"\x13AuditAnnotateConfig\x12a\n" +
	"\vannotations\x18\x01 \x03(\v2?.workflow.plugins.audit.v1.AuditAnnotateConfig.AnnotationsEntryR\vannotations\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x12AuditAnnotateInput\x12`\n" +
	"\vannotations\x18\x01 \x03(\v2>.workflow.plugins.audit.v1.AuditAnnotateInput.AnnotationsEntryR\vannotations\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x01\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05since\x18\x01 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x02 \x01(\tR\x05until\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"\x0e\n" +
	"\fStatsRequest\"\r\n" +
	"\vInfoRequest\"\xbc\x03\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12\x1f\n" +
	"\vpipeline_id\x18\x05 \x01(\tR\n" +
	"pipelineId\x12\x1b\n" +
	"\tstep_name\x18\x06 \x01(\tR\bstepName\x12\x14\n" +
	"\x05actor\x18\a \x01(\tR\x05actor\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12+\n" +
	"\x04data\x18\t \x01(\v2\x17.google.protobuf.StructR\x04data\x12X\n" +
	"\vannotations\x18\n" +
	" \x03(\v26.workflow.plugins.audit.v1.AuditEvent.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x10AuditQueryOutput\x12=\n" +
	"\x06events\x18\x01 \x03(\v2%.workflow.plugins.audit.v1.AuditEventR\x06events\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x90\x01\n" +
	"\x11AuditExportOutput\x12\x1a\n" +
	"\bexported\x18\x01 \x01(\x05R\bexported\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x1f\n" +
	"\vbytes_total\x18\x04 \x01(\x05R\n" +
	"bytesTotal\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\xe4\x01\n" +
	"\x13AuditAnnotateOutput\x12a\n" +
	"\vannotations\x18\x01 \x03(\v2?.workflow.plugins.audit.v1.AuditAnnotateOutput.AnnotationsEntryR\vannotations\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\rQueryResponse\x12=\n" +
	"\x06events\x18\x01 \x03(\v2%.workflow.plugins.audit.v1.AuditEventR\x06events\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"[\n" +
	"\rStatsResponse\x12\x18\n" +
	"\adropped\x18\x01 \x01(\x03R\adropped\x12\x1a\n" +
	"\bbuffered\x18\x02 \x01(\x05R\bbuffered\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05error\"\x8b\x01\n" +
	"\x10SinkInfoResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"table_name\x18\x04 \x01(\tR\ttableName\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBKZIgithub.com/GoCodeAlone/workflow-plugin-audit/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_audit_proto_rawDescOnce sync.Once
	file_internal_contracts_audit_proto_rawDescData []byte
)

func file_internal_contracts_audit_proto_rawDescGZIP() []byte {
	file_internal_contracts_audit_proto_rawDescOnce.Do(func() {
		file_internal_contracts_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_audit_proto_rawDesc), len(file_internal_contracts_audit_proto_rawDesc)))
	})
	return file_internal_contracts_audit_proto_rawDescData
}

var file_internal_contracts_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_contracts_audit_proto_goTypes = []any{
	(*CollectorConfig)(nil),     // 0: workflow.plugins.audit.v1.CollectorConfig
	(*S3SinkConfig)(nil),        // 1: workflow.plugins.audit.v1.S3SinkConfig
	(*DBSinkConfig)(nil),        // 2: workflow.plugins.audit.v1.DBSinkConfig
	(*AuditQueryConfig)(nil),    // 3: workflow.plugins.audit.v1.AuditQueryConfig
	(*AuditQueryInput)(nil),     // 4: workflow.plugins.audit.v1.AuditQueryInput
	(*AuditExportConfig)(nil),   // 5: workflow.plugins.audit.v1.AuditExportConfig
	(*AuditExportInput)(nil),    // 6: workflow.plugins.audit.v1.AuditExportInput
	(*AuditAnnotateConfig)(nil), // 7: workflow.plugins.audit.v1.AuditAnnotateConfig
	(*AuditAnnotateInput)(nil),  // 8: workflow.plugins.audit.v1.AuditAnnotateInput
	(*QueryRequest)(nil),        // 9: workflow.plugins.audit.v1.QueryRequest
	(*StatsRequest)(nil),        // 10: workflow.plugins.audit.v1.StatsRequest
	(*InfoRequest)(nil),         // 11: workflow.plugins.audit.v1.InfoRequest
	(*AuditEvent)(nil),          // 12: workflow.plugins.audit.v1.AuditEvent
	(*AuditQueryOutput)(nil),    // 13: workflow.plugins.audit.v1.AuditQueryOutput
	(*AuditExportOutput)(nil),   // 14: workflow.plugins.audit.v1.AuditExportOutput
	(*AuditAnnotateOutput)(nil), // 15: workflow.plugins.audit.v1.AuditAnnotateOutput
	(*QueryResponse)(nil),       // 16: workflow.plugins.audit.v1.QueryResponse
	(*StatsResponse)(nil),       // 17: workflow.plugins.audit.v1.StatsResponse
	(*SinkInfoResponse)(nil),    // 18: workflow.plugins.audit.v1.SinkInfoResponse
	nil,                         // 19: workflow.plugins.audit.v1.AuditAnnotateConfig.AnnotationsEntry
	nil,                         // 20: workflow.plugins.audit.v1.AuditAnnotateInput.AnnotationsEntry
	nil,                         // 21: workflow.plugins.audit.v1.AuditEvent.AnnotationsEntry
	nil,                         // 22: workflow.plugins.audit.v1.AuditAnnotateOutput.AnnotationsEntry
	(*structpb.Struct)(nil),     // 23: google.protobuf.Struct
}
var file_internal_contracts_audit_proto_depIdxs = []int32{
	12, // 0: workflow.plugins.audit.v1.AuditExportInput.events:type_name -> workflow.plugins.audit.v1.AuditEvent
	19, // 1: workflow.plugins.audit.v1.AuditAnnotateConfig.annotations:type_name -> workflow.plugins.audit.v1.AuditAnnotateConfig.AnnotationsEntry
	20, // 2: workflow.plugins.audit.v1.AuditAnnotateInput.annotations:type_name -> workflow.plugins.audit.v1.AuditAnnotateInput.AnnotationsEntry
	23, // 3: workflow.plugins.audit.v1.AuditEvent.data:type_name -> google.protobuf.Struct
	21, // 4: workflow.plugins.audit.v1.AuditEvent.annotations:type_name -> workflow.plugins.audit.v1.AuditEvent.AnnotationsEntry
	12, // 5: workflow.plugins.audit.v1.AuditQueryOutput.events:type_name -> workflow.plugins.audit.v1.AuditEvent
	22, // 6: workflow.plugins.audit.v1.AuditAnnotateOutput.annotations:type_name -> workflow.plugins.audit.v1.AuditAnnotateOutput.AnnotationsEntry
	12, // 7: workflow.plugins.audit.v1.QueryResponse.events:type_name -> workflow.plugins.audit.v1.AuditEvent
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_contracts_audit_proto_init() }
func file_internal_contracts_audit_proto_init() {
	if File_internal_contracts_audit_proto != nil {
		return
	}
	file_internal_contracts_audit_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_contracts_audit_proto_msgTypes[4].OneofWrappers = []any{}
	file_internal_contracts_audit_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_audit_proto_rawDesc), len(file_internal_contracts_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_audit_proto_goTypes,
		DependencyIndexes: file_internal_contracts_audit_proto_depIdxs,
		MessageInfos:      file_internal_contracts_audit_proto_msgTypes,
	}.Build()
	File_internal_contracts_audit_proto = out.File
	file_internal_contracts_audit_proto_goTypes = nil
	file_internal_contracts_audit_proto_depIdxs = nil
}
